project:
  type: website
  output-dir: docs
  resources:
  - CNAME
execute: 
  freeze: auto

website:
  title: "Psychological Science Accelerator"
  site-url: https://psysciacc.github.io
  repo-url: https://github.com/psysciacc/psysciacc.github.io
  image: images/logo.png
  favicon: images/favicon.ico
  navbar:
    logo: /images/logo.png
    logo-alt: "Green circle with 3 white chevrons like a fast-forward button"
    right:
      - text: Membership
        menu: 
          - join.qmd
          - text: "Current Members Login"
            aria-label: Current Members Login
            href: https://canvas.psysciacc.org/login/canvas
      - text: Policies
        menu: 
          - text: "Membership"
            aria-label: Membership
            href: join.qmd
          - text: "Code of Conduct"
            aria-label: Code of Conduct
            href: https://docs.google.com/document/d/1I81lPGTAPoK-ACAthQDBQhVkf3KJqwIamcTyLMM75kk/edit?tab=t.0#heading=h.bcf6vwg2u1v2
          - text: "Scientific Integrity"
            aria-label: Scientific Integrity
            href: https://docs.google.com/document/d/12UFYNHc31z81FAMv2f-_BCoX0eDof0-QvPN2cry7F88/edit?tab=t.0
          - text: "Mission and Core Values"
            aria-label: Mission and Core Values
            href: https://docs.google.com/document/d/143O4l9vl9FwUweK99I5nKviG6TbcO6eww6Es3rxQGS0/edit?tab=t.0
          - text: "Elections"
            aria-label: Elections
            href: https://docs.google.com/document/d/1aXjXwouFc6wvcyy7IFmEKGL0j2yxzYukyI_YFf6sZtM/edit?tab=t.0#heading=h.p1xd7vlghenh
          - text: "Scientific Criticism"
            aria-label: Scientific Criticism
            href: https://docs.google.com/document/d/1xyEchyyXDXGKpZsxQz82cJumYHEuqbodkrkr6CMZC7s/edit?tab=t.0#heading=h.ig1jhinfwhm
      - text: Studies
        menu: 
          - projects.qmd
          - affiliated.qmd
          - submit.qmd
          - text: "{{< ai google-scholar size=2x >}} Papers"
            aria-label: Google Scholar
            href: https://scholar.google.com/citations?user=yHWkiu4AAAAJ
      - text: Conferences
        menu:
          - conf-register.qmd
          - conf-previous.qmd
      - text: About Us
        menu: 
          - about.qmd
          - map.qmd
          - translation.qmd
          - media.qmd
          - contacts.qmd
          - news.qmd
          - funding.qmd
          - text: "{{< ai osf >}} OSF"
            aria-label: OSF
            href: https://osf.io/93qpg/
          - text: GitHub
            icon: github
            aria-label: GitHub
            href: https://github.com/psysciacc
          - text: "Twitter"
            icon: twitter
            aria-label: Twitter
            href: https://twitter.com/psysciacc
      - text: Donate
        menu: 
          - text: Patreon 
            href: https://patreon.com/psysciacc?utm_medium=unknown&utm_source=join_link&utm_campaign=creatorshare_creator&utm_content=copyLink
          - text: PayPal Charities
            href: https://www.paypal.com/fundraiser/charity/5217974
          - text: PayPal
            href: https://www.paypal.com/donate/?hosted_button_id=78JFLBZR2VPT4
  page-footer:
    background: primary
    right:
      - text: "{{< ai osf size=1x >}}"
        aria-label: OSF
        href: https://osf.io/93qpg/
      - icon: github
        aria-label: GitHub
        href: https://github.com/psysciacc
      - text: "{{< ai google-scholar size=2x >}}"
        aria-label: Google Scholar
        href: https://scholar.google.com/citations?user=yHWkiu4AAAAJ
      - icon: twitter
        aria-label: Twitter
        href: https://twitter.com/psysciacc
format:
  html:
    theme: 
      light: [flatly, styles.scss]
      dark: [darkly, styles.scss]
    include-in-header: 
      - text: "<script type='text/javascript' src='https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js'></script>"



